// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableLocalClassification": boolean;
      "maxCollectionRecommendations": number;
      "maxTagRecommendations": number;
      "includeAbstracts": boolean;
      "includeAutomaticTags": boolean;
      "excludedCollectionPaths": string;
      "showExplanations": boolean;
      "confirmBeforeWrite": boolean;
      "remoteEnabled": boolean;
      "providerName": string;
      "baseURL": string;
      "apiKey": string;
      "model": string;
      "timeoutMs": number;
      "temperature": string;
      "maxOutputTokens": number;
      "sendAbstract": boolean;
      "sendSimilarAbstracts": boolean;
    };
  }
}
